[package]
name = "utp-tm4c"
version = "0.1.0"
authors = ["UT UTP <ut.utp.group@gmail.com>"]
edition = "2018"

# TODO: CI
# TODO: README
# TODO: MSRV
# TODO: CHANGELOG
# TODO: all the other keys
# TODO: lints and attributes for this crate

[dependencies]
cortex-m-rt = {version = "0.6.10", features = ["device"]}
cortex-m-semihosting = "0.3.3"
panic-halt = "0.2.0"

# TODO: All of the below should use crates.io published version instead of git repos.
lc3-device-support = { git = "https://github.com/ut-utp/prototype.git", branch = "staging", version = "0.1.0", default-features = false, features = ["no_std"]}
lc3-baseline-sim = { git = "https://github.com/ut-utp/prototype.git", branch = "staging", version = "0.1.0", default-features = false, features = ["no_std"] }
lc3-isa = { git = "https://github.com/ut-utp/prototype.git", branch = "staging", version = "0.1.0", default-features = false, features = ["no_std"] }
lc3-traits = { git = "https://github.com/ut-utp/prototype.git", branch = "staging", version = "0.1.0", default-features = false, features = ["no_std"]  }

tm4c123x-hal = { version = "0.9.0", features = ["rt"] }
tm4c123x = "0.9.0"
embedded-hal = "0.2.3"


[profile.release]
codegen-units = 1 # better optimizations
debug = true # symbols are nice and they don't increase the size on Flash
lto = true # better optimizations

